# Generated by Django 5.2.7 on 2025-10-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_due_date_task_deadline_rename_title_task_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='account',
        ),
    ]
