# Generated by Django 5.2.7 on 2025-10-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_user_id_task_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='account',
            new_name='user_id',
        ),
    ]
