# Generated by Django 5.2.7 on 2025-11-13 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_completed_at'),
        ('users', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_count', models.IntegerField(help_text='Number of tasks to complete')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Priority level of tasks to complete', max_length=20)),
                ('description', models.CharField(help_text='Challenge description', max_length=500)),
                ('start_date', models.DateTimeField(help_text='Challenge start date (Sunday 12:00 AM)')),
                ('deadline', models.DateTimeField(help_text='Challenge deadline (Saturday 11:59 PM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='users.account')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tasks.weeklychallenge')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
