# Generated by Django 5.2.7 on 2025-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_weeklychallenge_challengeparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
