# Generated by Django 5.2.7 on 2025-11-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_notify'),
        ('tasks', '0014_remove_event_end_date_remove_event_start_date_and_more'),
    ]

    operations = [
    ]
