# Generated by Django 5.2.7 on 2025-10-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamagotchi',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('state', models.CharField(default='idle', max_length=50)),
            ],
        ),
    ]
