# Generated by Django 5.2.7 on 2025-10-24 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamagotchi', '0001_initial'),
        ('users', '0005_account_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamagotchi',
            name='uid',
        ),
        migrations.AddField(
            model_name='tamagotchi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tamagotchi',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tamagotchi', to='users.account'),
            preserve_default=False,
        ),
    ]
