# Generated by Django 5.2.7 on 2025-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamagotchi', '0002_remove_tamagotchi_uid_tamagotchi_id_tamagotchi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamagotchi',
            name='health',
            field=models.FloatField(default=5.0),
        ),
    ]
