# Generated by Django 5.2.7 on 2025-11-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamagotchi', '0003_alter_tamagotchi_health 2'),
        ('tamagotchi', '0003_alter_tamagotchi_health'),
    ]

    operations = [
    ]
