# Generated by Django 5.2.7 on 2025-11-04 04:39

import tamagotchi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamagotchi', '0004_merge_20251103_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamagotchi',
            name='outfit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tamagotchi',
            name='unlocked_outfits',
            field=models.JSONField(default=tamagotchi.models.default_unlocked_outfits),
        ),
    ]
