# Generated by Django 5.2.7 on 2025-11-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamagotchi', '0005_tamagotchi_outfit_tamagotchi_unlocked_outfits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamagotchi',
            name='items',
        ),
    ]
