# Generated by Django 5.2.7 on 2025-10-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hashed_password',
            field=models.CharField(max_length=200),
        ),
    ]
