# Generated by Django 5.2.7 on 2025-10-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_hashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
