# Generated by Django 5.2.7 on 2025-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.JSONField(default=list),
        ),
    ]
